require('init-plugs')

require('settings')
require('theme')
require('keymaps')

require('plugins/autopairs')
require('plugins/cmp')
require('plugins/luasnip')
require('plugins/lsp')
require('plugins/null-ls')
require('plugins/tree')
require('plugins/telescope')
require('plugins/lualine')
require('plugins/treesitter')
